services:
  # MariaDB 資料庫
  db:
    image: mariadb:11
    container_name: badminton-forum-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-badmintonforumdb}
      MARIADB_USER: ${MARIADB_USER:-badmintonuser}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-BadmintonPass123}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-rootpass123}
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATION: utf8mb4_unicode_ci
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - badminton-network

  # .NET Core API
  api:
    build:
      context: ./BadmintonForum.API
      dockerfile: Dockerfile
      target: development
    container_name: badminton-forum-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5246
      ConnectionStrings__DefaultConnection: "Server=db;Database=${MARIADB_DATABASE:-badmintonforumdb};User=${MARIADB_USER:-badmintonuser};Password=${MARIADB_PASSWORD:-BadmintonPass123};"
      JwtSettings__Secret: ${JWT_SECRET:-ThisIsAVerySecretKeyForJWTTokenGenerationPleaseChangeInProduction}
      JwtSettings__Issuer: ${JWT_ISSUER:-BadmintonForumAPI}
      JwtSettings__Audience: ${JWT_AUDIENCE:-BadmintonForumClient}
      JwtSettings__ExpirationInDays: ${JWT_EXPIRATION_DAYS:-7}
      Email__UseConsoleEmail: "true"
      Email__BaseUrl: ${EMAIL_BASE_URL:-http://localhost:5173}
      GoogleAuth__ClientId: ${GOOGLE_CLIENT_ID:-YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com}
    ports:
      - "${API_PORT:-5246}:5246"
    volumes:
      - ./BadmintonForum.API:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
      - dotnet_tools:/root/.dotnet/tools
      - ./BadmintonForum.API/wwwroot/uploads:/app/wwwroot/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - badminton-network
    command: ["./docker-entrypoint.sh"]

  # Vue.js 前端
  web:
    build:
      context: ./badminton-forum-vue
      dockerfile: Dockerfile
      target: development
    container_name: badminton-forum-web
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5246/api}
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com}
    ports:
      - "${WEB_PORT:-5173}:5173"
    volumes:
      - ./badminton-forum-vue:/app
    depends_on:
      - api
    networks:
      - badminton-network

  # Vuestic Admin 後台管理系統
  admin:
    build:
      context: ./badminton-forum-admin
      dockerfile: Dockerfile
      target: development
    container_name: badminton-forum-admin
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5246/api}
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com}
      VITE_APP_NAME: ${ADMIN_APP_NAME:-羽球論壇管理後台}
    ports:
      - "${ADMIN_PORT:-5174}:5174"
    volumes:
      - ./badminton-forum-admin:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - badminton-network

  # Adminer (資料庫管理介面，選用)
  adminer:
    image: adminer:latest
    container_name: badminton-forum-adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - badminton-network
    profiles:
      - tools

networks:
  badminton-network:
    driver: bridge

volumes:
  mariadb_data:
  dotnet_tools: