services:
  # PostgreSQL 資料庫
  db:
    image: postgres:16-alpine
    container_name: badminton-forum-db
    environment:
      POSTGRES_DB: badmintonforumdb
      POSTGRES_USER: badmintonuser
      POSTGRES_PASSWORD: BadmintonPass123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U badmintonuser -d badmintonforumdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - badminton-network

  # .NET Core API
  api:
    build:
      context: ./BadmintonForum.API
      dockerfile: Dockerfile
      target: production
    container_name: badminton-forum-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5246
      ConnectionStrings__DefaultConnection: "Host=db;Database=badmintonforumdb;Username=badmintonuser;Password=BadmintonPass123"
      JwtSettings__Secret: ThisIsAVerySecretKeyForJWTTokenGenerationPleaseChangeInProduction
      JwtSettings__Issuer: BadmintonForumAPI
      JwtSettings__Audience: BadmintonForumClient
      JwtSettings__ExpirationInDays: 7
      Email__UseConsoleEmail: "true"
    ports:
      - "5246:5246"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - badminton-network

  # Vue.js 前端
  web:
    build:
      context: ./badminton-forum-vue
      dockerfile: Dockerfile
      target: production
    container_name: badminton-forum-web
    environment:
      VITE_API_URL: http://localhost:5246/api
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - badminton-network

networks:
  badminton-network:
    driver: bridge